name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set toolchain
        run: |
          rustup set profile minimal
          rustup override set stable

      - uses: Swatinem/rust-cache@v2.0.0

      - name: Rustfmt check
        run: |
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Clippy check
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Run `cargo test` on workspace
        run: cargo test --all-features --all-targets